domain/src/main/java/com/onlydust/marketplace/indexer/domain/exception/NotFound.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/raw/RawCheckRuns.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/CacheWriteRawStorageReaderDecorator.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/RawStorageReader.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/IndexingService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/stubs/RawStorageRepositoryStub.java, infrastructure/github/pom.xml, infrastructure/github/src/main/java/com/onlydust/marketplace/indexer/github/GithubHttpClient.java, infrastructure/github/src/main/java/com/onlydust/marketplace/indexer/github/adapters/GithubRawStorageReader.java, infrastructure/pom.xml, infrastructure/postgres/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresRawStorageRepository.java
- first implementation of github client
- handle 404
=> [B-1015] Implement Github API adapter

bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubWebhookIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/IntegrationTest.java, bootstrap/src/test/resources/db_init_script/create_indexer_schema.sql, scripts/initdb.d/create_indexer_schema.sql
- update liquibase default schema
- fix integration test
=> Change liquibase default schema

bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/WebSecurityAdapter.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/IndexingService.java, infrastructure/github/src/main/java/com/onlydust/marketplace/indexer/github/GithubHttpClient.java, infrastructure/github/src/main/java/com/onlydust/marketplace/indexer/github/GithubPage.java, infrastructure/github/src/main/java/com/onlydust/marketplace/indexer/github/GithubPageLinks.java, infrastructure/github/src/main/java/com/onlydust/marketplace/indexer/github/adapters/GithubRawStorageReader.java, infrastructure/github/src/test/java/com/onlydust/marketplace/indexer/github/GithubPageLinksTest.java
- fix swagger permissions
- add logging in indexing service
- fix github streaming
- stream issues
=> Fix github streaming

application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/IndexesRestApi.java, application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/IssuesRestApi.java, application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/PullRequestsRestApi.java, application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/UsersRestApi.java, application/rest.api/src/main/resources/marketplace-indexer-contract.yaml, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/IssueIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/PullRequestIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/RepoJobIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/UserIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/UserJobIndexingIT.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/RepoIndexingJobTriggerRepository.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/UserIndexingJobTriggerRepository.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/stubs/RepoIndexingJobTriggerRepositoryStub.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/stubs/UserIndexingJobTriggerRepositoryStub.java, infrastructure/postgres/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresRepoIndexingJobTriggerRepository.java, infrastructure/postgres/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresUserIndexingJobTriggerRepository.java, infrastructure/postgres/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/RepoIndexingJobTriggerEntity.java, infrastructure/postgres/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/UserIndexingJobTriggerEntity.java, infrastructure/postgres/src/main/resources/db/changelog/changelogs/00000007_rename-job-triggers-column.sql, infrastructure/postgres/src/main/resources/db/changelog/db.changelog-master.yaml
- remove unused endpoints
- user job indexing rest api
- repo job indexing rest api
- use Long in rest api for github ids
=> [B-1019] Implement missing REST endpoints

.github/workflows/backend-ci.yml, application/cron/src/main/java/com/onlydust/marketplace/indexer/cron/JobScheduler.java, application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/IssuesRestApi.java, application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/PullRequestsRestApi.java, application/rest.api/src/main/java/com/onlydust/marketplace/indexer/rest/api/UsersRestApi.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/RestApiConfiguration.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/Indexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/IssueIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/PullRequestIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/RefreshJobScheduler.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/RepoIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/UserIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/IssueIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/PullRequestIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/RepoIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/RepoRefreshJobService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/UserIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/UserRefreshJobService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/IndexingServiceTest.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/RepoJobServiceTest.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/UserJobServiceTest.java, infrastructure/quartz/src/main/java/com/onlydust/indexer/infrastructure/quartz/adapters/RepoRefresherJob.java, infrastructure/quartz/src/main/java/com/onlydust/indexer/infrastructure/quartz/adapters/UserRefresherJob.java
- interface segregation for indexers
- interface segregation in refresh jobs
=> Interface segregation

bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubWebhookIT.java, bootstrap/src/test/resources/github/webhook/events/installation_created.json, bootstrap/src/test/resources/github/webhook/events/installation_deleted.json, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/raw/RawInstallationEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/EventProcessorService.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/JobTriggerEventListener.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresInstallationEventListener.java
- refactor installation created test
- handle github app deleted event
=> [B-1032] Handle installation deleted event

bootstrap/src/main/resources/logback.xml, pom.xml
- json logging for datadog
- remove unused dependency
=> Improve logging for datadog

bootstrap/src/main/resources/application.yaml, bootstrap/src/main/resources/logback.xml, bootstrap/src/test/resources/logback-test.xml
- use default logger in local
- export metrics to datadog
=> Enable datadog monitoring

bootstrap/pom.xml, bootstrap/src/main/resources/application.yaml
- add micrometer dependency
- add correct datadog uri
=> Fix metric export to datadog

bootstrap/pom.xml, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/resources/wiremock/github/__files/rate_limit.json, bootstrap/src/test/resources/wiremock/github/mappings/rate_limit.json, domain/pom.xml, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/RateLimit.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/CleanRepo.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/CacheReadRawStorageReaderDecorator.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/CacheWriteRawStorageReaderDecorator.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/RateLimitService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/RawStorageReader.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/RawStorageRepository.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/RateLimitGuardedRepoIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/RepoIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/monitoring/MonitoredIssueIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/monitoring/MonitoredPullRequestIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/monitoring/MonitoredRepoIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/monitoring/MonitoredUserIndexer.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/IndexingServiceTest.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/stubs/RawStorageRepositoryStub.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/adapters/GithubRateLimitServiceAdapter.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/adapters/GithubRawStorageReader.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/entities/RateLimitResponse.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresRawStorageRepository.java, pom.xml
- monitor indexed items
- monitor github rate limit
- stream pull requests and issues to limit ram usage
=> More monitoring + enhance indexer perfs

bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/PullRequestIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/RepoJobIndexingIT.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/raw/RawPullRequestClosingIssues.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/PullRequestIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/RateLimitGuardedFullRepoIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/exposers/PullRequestContributionExposer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/monitoring/MonitoredPullRequestIndexer.java
- remove println
- remove @Transactional
- add logs
=> Some fixes

bootstrap/src/main/resources/application.yaml, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/GithubHttpClient.java
- increase log level
- implement retry mechanism for github fetch errors
- configurable retry strategy
=> Retry upon Github error

bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubWebhookIT.java, bootstrap/src/test/resources/db_init_script/create_indexer_schema.sql, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/RepoIndexingJobRepositoryComposite.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresOldRepoIndexingJobRepository.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/OldRepoIndexesEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/OldRepoIndexesEntityRepository.java
- create old repo indexes repository
- plug old repo index repository using a composite
=> [B-1060] plug the create update project with the old indexer

domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/exposition/Contribution.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/ContributionEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubCodeReviewEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubIssueEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubPullRequestEntity.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000014_add_repo_info_in_sub_tables.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- move projection logic in db layer
- add repo owner login and repo name in pr and issues
- add pr info in code reviews table
=> [B-1120] Add repo name and repo owner name in issues/pull_requests/code_reviews

bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/exposition/IssueStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/exposition/PullRequestStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/exposers/IssueExposer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/exposers/PullRequestExposer.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/IndexingServiceTest.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresIssueStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresPullRequestStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/exposition/GithubIssueRepository.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/exposition/GithubPullRequestRepository.java
- expose pull request even if no contribution found
- expose issue even if no contribution found
=> [B-1112] Index other PR/other issue that are not contributions

application/rest-api-adapter/src/main/java/com/onlydust/marketplace/indexer/rest/api/IndexesRestApi.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/RestApiConfiguration.java
=> make refresh endpoint synchronous

Procfile, application/cli-adapter/pom.xml, application/cli-adapter/src/main/java/com/onlydust/marketplace/indexer/cli/RepoRefreshCliAdapter.java, application/cron-adapter/src/main/java/com/onlydust/marketplace/indexer/cron/JobScheduler.java, application/rest-api-adapter/src/main/java/com/onlydust/marketplace/indexer/rest/api/IndexesRestApi.java, application/rest-api-adapter/src/main/resources/marketplace-indexer-contract.yaml, bootstrap/pom.xml, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/CliConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/GithubWebhookConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/MarketplaceIndexerWebMvcConfigurer.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/SwaggerConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/WebSecurityAdapter.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/WebSecurityConfiguration.java, bootstrap/src/main/resources/application-cli.yaml, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/IntegrationTest.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/raw/CacheReadRawStorageReaderDecorator.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/IndexingServiceTest.java, heroku/start-dyno-with-datadog-apm.sh, pom.xml
- activate adapters with spring profiles
- create cli adapter with repo refresh job
- remove refresh from rest api
- restore cache read repo pr and issue streaming
- use cache only for refresh
=> Refresh repo using cli

bootstrap/src/main/resources/logback.xml, domain/src/main/java/com/onlydust/marketplace/indexer/domain/jobs/RepoIndexerJob.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/RepoIndexingJobStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/RepoIndexingJobStorageComposite.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/RepoRefreshJobService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/RepoJobServiceTest.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresOldRepoIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresRepoIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/RepoIndexingJobEntityRepository.java
- fix suspended installation + outdated repos
- add logs
- add debug logs for local and cli
=> Fix some issues related to refresh cli

application/rest-api-adapter/src/main/java/com/onlydust/marketplace/indexer/rest/api/UsersRestApi.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/UserIndexingIT.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/UserIndexingJobStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/UserRefreshJobService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/RepoJobServiceTest.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/UserJobServiceTest.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresUserIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/UserIndexingJobEntityRepository.java
- check users to refresh more regularly
- add user indexing job upon user indexing
=> Fix user indexing

application/cli-adapter/src/main/java/com/onlydust/marketplace/indexer/cli/RepoRefreshCliAdapter.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/RepoIndexingJobEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/UserIndexingJobEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/ContributionEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubAccountEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubAppInstallationEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubCodeReviewEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubIssueEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubPullRequestEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubRepoEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/InstallationEvent.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/Issue.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/PullRequest.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/PullRequestClosingIssues.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/PullRequestCommits.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/PullRequestReview.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/Repo.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/RepoCheckRuns.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/RepoLanguages.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/User.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/raw/UserSocialAccounts.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000027_update_tech_updated_at_triggers.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, temp
- rename bean
- manage tech columns by postgres
=> Manage tech columns by postgres to avoid too many updates

bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubWebhookIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/RepoJobIndexingIT.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/RepoIndexingJobStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/RepoIndexingJobStorageComposite.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/events/InstallationEventProcessorService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/RepoRefreshJobService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/InstallationEventTest.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresOldRepoIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresRepoIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/RepoIndexingJobEntity.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/RepoIndexingJobEntityRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000030_add_repo_indexing_mode.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- add full indexing mode in repo indexing jobs
- set full indexing mode only when linking to project
- only select full indexing repos for indexer
=> [B-1160] Only index contributions on repo that are actually linked to projects

application/rest-api-adapter/src/main/java/com/onlydust/marketplace/indexer/rest/api/IndexesRestApi.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/FullRepoJobIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/LightRepoJobIndexingIT.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/jobs/RepoIndexerJob.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/RepoIndexingJobTrigger.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/indexers/FullRepoIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/jobs/RepoIndexingJobScheduler.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/jobs/RepoRefreshJobManager.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/jobs/UserIndexingJobScheduler.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/in/jobs/UserRefreshJobManager.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/RepoIndexingJobStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/jobs/RepoIndexingJobStorageComposite.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/exposers/RepoContributorsExposer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/guards/RateLimitGuardedFullRepoIndexer.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/indexers/FullRepoIndexingService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/RepoIndexingJobSchedulerService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/RepoRefreshJobService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/SequentialJobComposite.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/UserIndexingJobSchedulerService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/jobs/UserRefreshJobService.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/monitoring/MonitoredFullRepoIndexer.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/IndexingServiceTest.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/RepoJobServiceTest.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresOldRepoIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresRepoIndexingJobStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/RepoIndexingJobEntityRepository.java
- create integration test
- remove full repo indexer
- split repo scheduler from repo manager
- create sequential job composite
- index repo in full and light mode
=> [B-1162] Index repos in light mode

bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubInstallationEventsIT.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresGithubAppInstallationStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubAppInstallationEntity.java
- Revert "deduplicate authorized repos"
- handle duplicate repos added for a given installation
=> Fix duplicate repos added for a given installation

bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/IntegrationTest.java, bootstrap/src/test/resources/scripts/backup_db.sh, bootstrap/src/test/resources/scripts/clean.sql, bootstrap/src/test/resources/scripts/restore_db.sh
- speed up integration tests
- backup/restore db between each test
=> Speed-up integration tests

bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/MarketplaceIndexerApplication.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubInstallationEventsIT.java, domain/pom.xml, domain/src/main/java/com/onlydust/marketplace/indexer/domain/jobs/InstallationEventsInboxJob.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/jobs/OtherEventsInboxJob.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/repositories/raw/EventsInboxEntityRepository.java
- dot not block events dequeuing
- retry events processing
=> Improve events processing error management

Procfile, application/cli-adapter/pom.xml, application/cli-adapter/src/main/java/com/onlydust/marketplace/indexer/cli/CommitIndexerCliAdapter.java, application/cli-adapter/src/main/java/com/onlydust/marketplace/indexer/cli/RepoRefreshCliAdapter.java, bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/CliConfiguration.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/exposition/GithubPullRequest.java
- **add cli discriminator**
- **fix Procfile to allow cli arguments**
- **create binary to re-index all commits**
=> [B-1530] Create a batch to index historical pull requests modified files

domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/exposition/GithubPullRequest.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/models/exposition/GithubPullRequestTest.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000045_clean_file_extensions.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **fix file extensions computation**
- **clean-up exposition table**
=> Fix file extension computation

bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubInstallationEventsIT.java, bootstrap/src/test/resources/github/webhook/events/installation/new_permissions_accepted.json, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationAddedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationCreatedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationDeletedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationNewPermissionsAcceptedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationRemovedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationSuspendedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/InstallationUnsuspendedEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/exposition/GithubAppInstallation.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/raw/RawInstallation.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/ports/out/exposition/GithubAppInstallationStorage.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/events/InstallationEventProcessorService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/stubs/InstallationStorageStub.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/adapters/PostgresGithubAppInstallationStorage.java, infrastructure/postgres-adapter/src/main/java/com/onlydust/marketplace/indexer/postgres/entities/exposition/GithubAppInstallationEntity.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000052_add_installation_permissions.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **expose github app installation permissions**
- **handle new permissions accepted event**
=> [B-1977] Expose installation permissions

bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/UserIndexingIT.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/UserJobIndexingIT.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/Fetcher.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/GithubConfig.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/GithubConfiguration.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/GithubHttpClient.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/GithubPage.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/GithubPageLinks.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/HttpFetcher.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/RedirectionHandledHttpFetcher.java, infrastructure/github-api-adapter/src/main/java/com/onlydust/marketplace/indexer/github/RetriedOnErrorHttpFetcher.java
- **reduce log level**
- **add retry integration test**
- **refactor special http status handling**
- **handle more retry statuses**
=> Improve indexer logging

infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000053_add_missing_indexes.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
Fix perf issue on a query that takes 40% of all exec time on the DB
=> Add missing indexes

bootstrap/src/main/java/com/onlydust/marketplace/indexer/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/test/java/com/onlydust/marketplace/indexer/bootstrap/it/GithubRepositoryEventsIT.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/models/clean/github_app_events/RepositoryEvent.java, domain/src/main/java/com/onlydust/marketplace/indexer/domain/services/events/RepositoryEventProcessorService.java, domain/src/test/java/com/onlydust/marketplace/indexer/domain/services/events/RepositoryEventProcessorServiceTest.java
- **small refactoring**
- **index repos from events**
=> Index repos from events
